### PR TITLE
Cleanup git status & build

### PR DESCRIPTION
**Pull request by olaf-mandel**
* Clean up .gitignore so status shows clean after build even for VPATH builds
* Convert to non-recursive make as per Peter Millers "Recursive Make Considered Harmful"

The second patch fixes, among others, the problem with this invokation: `make install DESTDIR=relpath` (created `include/relpath` and `src/relpath` before).

### CODE REVIEW

**Comment by tommie** [comment]
Recursion is idiomatic in automake and should cause no issues. Note that DESTDIR is an absolute path per documentation: https://www.gnu.org/software/automake/manual/html_node/DESTDIR.html

**Comment by olaf-mandel** [comment]
You are correct about `DESTDIR` being documented only for absolute paths: I did not read that page of the manual. But I stand by my claim that a single Makefile enables the extra "feature" of relative paths for `DESTDIR`.

And the recursive make vs single Makefile is a bit like emacs vs vim or any other number of flamewars where personal preference comes into play: [Peter Miller’s paper](http://aegis.sourceforge.net/auug97.pdf) makes quite a few telling points why recursive make is to be avoided (and is thus [referenced in the Automake manual](https://www.gnu.org/software/automake/manual/html_node/Alternative.html)). But none of Peter Millers arguments (except for speed, a very little bit) apply to this project.

So there is no _need_ to convert to non-recursive make: I just use it as a matter-of-course because sometimes the difference in speed is profound. Will you merge this or should I prepare a new pull request with just the .gitignore cleanup for `VPATH` builds and replacing the hardcoded `.o` with `OBJEXT`?

**Comment by tommie** [comment]
Agreed on the flamewar argument. Sorry for my brevity. No harm intended.

I do like having the makefiles close to the code, so would prefer keeping the recursive setup, unless there is a concrete issue. I assume you use the `DESTDIR` in some build automation script rather than entered manually, otherwise I'd suggest using `./configure --prefix=<path>` instead to avoid having to retype. At least `--prefix` fails if not used with an absolute path. Much better than the silent failure of `DESTDIR`...

Yes, please split off the VPATH and OBJEXT fixes.

**Comment by olaf-mandel** [comment]
Created a new pull request: #11, closing this one.

**Pull request closed without merging**
