### PR TITLE
Fix detection of xtensa ar tool

### PR DESCRIPTION
**Pull request by hebnern**
Fixes build error referenced in issue #5

### CODE REVIEW

**Comment by jholster** [comment]
I can confirm that this patch works on OS X Yosemite.

**Comment by bjpirt** [comment]
I can also confirm this patch works - please merge!

**Comment by straend** [comment]
Confirms that this works on Yosemite 10.10.2.

**Comment by hebnern** [comment]
Hey @tommie any hope of getting this merged so that building [esp-open-sdk](https://github.com/pfalcon/esp-open-sdk) is less of a pain on OS X?

**Comment by tommie** [comment]
Ouch, sorry. For some reason I didn't receive email notifications for this repo. Looks good.

**Comment by hebnern** [comment]
Sweet, thanks!

**Comment by MacDada** [comment]
Well, I still have the problem: https://github.com/pfalcon/esp-open-sdk/issues/41

**Pull request merged**
